version: "3.7"
services:
  subway_monitor:
    image: "subway_monitor"
    container_name: subway_monitor
    environment:
      - >
        JAVA_TOOL_OPTIONS=
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -XX:+UseContainerSupport
        -Xlog:gc
        -Xms256m
        -Xmx256m

    ports:
      - 8080:8080
      - 5005:5005
    networks:
      default:
        aliases:
          - "subway_monitor.subway_monitor"
    depends_on:
      - postgres_subway_monitor

  postgres_subway_monitor:
    image: postgres:12.2
    container_name: postgres_subway_monitor
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=subway_monitor
    ports:
      - 5432:5432
