spring:
  profiles.active: development

---

spring:
  profiles: development

  datasource:
    url: jdbc:postgresql://postgres_subway_monitor:5432/subway_monitor
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    locations: classpath:sql/db/migration

  resources:
    static-locations: "classpath:/static/"

server:
  port: 8080
  web:
    cors:
      allowed-origins: "http://localhost:3000"

logging:
  config: classpath:logback-spring.xml
  file: ./subway_monitor.log

application:
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000
  schedulers:
    verificationTask:
      cron-expression: "0 */3 * * * *"
    pingTask:
      cron-expression: "0 */3 * * * *"

monitors:
  metro-service.url: https://www.viaquatro.com.br/generic/Main

  ping.url: http://localhost:8080/v1/ping

---

spring:
  profiles: prod

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    locations: classpath:sql/db/migration

  resources:
    static-locations: "classpath:/static/"

server:
  port: ${PORT}
  web:
    cors:
      allowed-origins: "http://localhost:3000"

logging:
  config: classpath:logback-spring.xml
  file: ./subway_monitor.log

application:
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000
  schedulers:
    verificationTask:
      cron-expression: "0 */3 * * * *"
    pingTask:
      cron-expression: "0 */3 * * * *"

monitors:
  metro-service.url: https://www.viaquatro.com.br/generic/Main

  ping.url: https://api-subway-monitor-bb0c5df07afb.herokuapp.com/v1/ping

---

spring:
  profiles: test

  datasource:
    url: jdbc:h2:mem:subway_monitor;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS subway_monitor
    username: sa
    password:
    testWhileIdle: true
    validationQuery: SELECT 1

  flyway:
    enabled: false

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

server:
  port: 8080
  web:
    cors:
      allowed-origins: "http://localhost:3000"

logging:
  config: classpath:logback-spring.xml
  file: ./subway_monitor.log

application:
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000
  schedulers:
    verificationTask:
      cron-expression: "0 0 0 31 2 *"
    pingTask:
      cron-expression: "0 0 0 31 2 *"

monitors:
  metro-service.url: https://www.viaquatro.com.br/generic/Main

  ping.url: http://localhost:8080/v1/ping

---
