spring:
  profiles.active: development

---

spring:
  profiles: development

  datasource:
    url: jdbc:postgresql://postgres_subway_monitor:5432/subway_monitor
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  file: ./subway_monitor.log

metro-service.url: http://www.viaquatro.com.br/generic/Main/LineStatus

---

spring:
  profiles: prod

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT}

logging:
  config: classpath:logback-spring.xml
  file: ./subway_monitor.log

metro-service.url: http://www.viaquatro.com.br/generic/Main/LineStatus
